extends:
  - eslint:recommended
  - plugin:react/recommended
env:
  node: true
  browser: true
plugins:
  - compat
  - react
  - react-hooks
parser: babel-eslint
parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    legacyDecorators: true
rules:
  no-console: 0
  compat/compat: 2
  max-nested-callbacks: 0
  no-warning-comments: 0
  require-jsdoc: 0
  max-len: 0
  object-curly-spacing: 0
  one-var: 0
  arrow-parens: 0
  no-var: 2
  prefer-const: 2
  no-confusing-arrow: 2
  prefer-arrow-callback: 2
  switch-colon-spacing: 0
  no-unused-vars:
    - error
    - varsIgnorePattern: ^_
  sort-keys:
    - error
    - asc
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
globals:
  Promise: true
settings:
  react:
    version: detect
